name: 'My First GitHub Actions'

on: [ 'push', 'pull_request' ]

jobs:
  first_job:
    name: 'First Job'

    runs-on: ubuntu-latest

    steps:
      - name: Say Hello from First Job
        shell: bash
        run: |
          echo "Hello World"
  second_job:
    name: 'Second Job'
    needs: first_job

    runs-on: ubuntu-latest

    steps:
      - name: Say Hello from Second Job
        shell: bash
        run: |
          echo "Lorm Ipsum"
  third_job:
    name: 'Third Job'
    needs: first_job

    runs-on: ubuntu-latest

    steps:
      - name: Say Hello from Third Job
        shell: bash
        run: |
          echo "Lorm Ipsum"