name : 'My First Githob Actions'

on: push

jobs:

  first_job:
    name: 'First Job'
    runs-on: ubuntu-latest

    steps:
      - name: Mask output value
        id: first
        shell: bash
        run: |
          value1='This is the first secret value'

          echo "::add-mast::$value1"
          echo "::set-output name=first_value::$value1"

      - name: Check output value
        shell: bash
        run: |
  
          echo "first value: ${{ steps.first.outputs.first_value }}"